"""empty message

Revision ID: 070e0893a953
Revises: b3d327989987
Create Date: 2023-03-11 22:11:55.651903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070e0893a953'
down_revision = 'b3d327989987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
